Adding Practice 2 and 3
alunos-fatec-sjc/linguagem-de-programacao pull request #1
Opened 2019-08-31 12:38 UTC by joaocruz19

I'm adding the exercises of practices 2 and 3.

2019-08-31 16:10 UTC, vhoyer requested changes
I hope you don't mind :sweat_smile: but I took a look at your PR and I have _some_ considerations hehe :sweat_smile: may be a smaller PR would be better next time, but thanks for your time, I really apreciate your contribution :smile:

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-02/_
> +
hey man, I was wondering if you really want to do this in English, like to train? I mean, this is for brazilians students after all, so other than to train english writing, I don't see why do the reviews in English, but I will follow you on this one. :D

Sooo, could I ask you why you added those empty files named `_`?

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-02/ex1.c
> +#include<stdlib.h>
hey, you don't actually need this `stdlib.h` imported for this file, you can remove it
```suggestion
```

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-02/ex1.c
> +int primo(int n);
if your function is created before the `main` function, you don't need to declare that this exists, so this line, can too, be removed
```suggestion
```

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-02/ex1.c
> +    return 1;
with the main function, you genereally want to always return 0, because any number returned from `main` that is different than `0` is considered to be an error, so when you return `1`, the OS assumes (and tell the user) that the program ended with an error.

```suggestion
    return 0;
```

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-02/ex2.c
> +int primo(int n);
same thing applies here to, for those 2 lines, could you please take a look at the other files to unessessary imports and function declarations like this? thanks in advance xD

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-02/ex2.c
> +int primo(int n)
it's  probably better to return a `bool` from this function since it always return or `1` or `0`. And also, as the function always return a true or false (or a 0 or 1), I'd rename the function to explicitly tell the reader that this returns a true/false value, as a good practice, I always see an `isSomething` in the name of the function like this:

```suggestion
bool is_prime(int n)
```
(I also changed the name of the function from portuguese to english because of personal taste, and because writing `e_primo` is strange :stuck_out_tongue:)

and where you return 0, you change to `return false` and return 1 to `return true`

```diff
-return 0;
+return false;
```

```diff
-return 1;
+return true;
```

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-02/ex2.c
> +        if(primo(i) == 1){
here as the 1 and 0 is a truthy and falsy values (respectively) you can omit the `== 1`
```suggestion
        if(primo(i)){
```

also if you change the function signature (return type and name) like I suggested, you kinda have to take this out, otherwise you'd endup with something like `if (isPrime(i) == true)` which is just silly/reduntant

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-02/ex2.c
> +    printf("Soma dos %d primeiro n�meros primos: %d", n, soma);
```suggestion
    printf("Soma dos %d primeiro números primos: %d\n", n, soma);
```

it's always a good thing end the sentences with a line break, otherwise the output of your program on the command line gets messed up

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-02/ex2.c
> +    return 1;
same thing with this return, defautls to return zero, its better xD could you check the other files for this pattern too?

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-02/ex3.c
> +int n_divisores(int n)
It's never a good thing to abbreviate function names or variable names, as the programs grow in size and complexity, your programs will begin to get more and more complicated to read, if your function names are cristal clear to read out loud, is makes it easier to understand your program, I am used to code like a psycho is reading my code and he knows where I live, and he will get very mad if he don't understands my program :joy: 

```suggestion
int counta_divisores(int n)
```

```suggestion
int count_dividers(int n)
```

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-02/ex3.c
> +            cont++;
again as good practice, I find it always better to define explicitly the start and and of a block with `{` and `}`. This leads to less errors when the project grows in size

```c
if(n % i == 0) {
    cont++;
}
```

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-02/ex5.c
> +
```suggestion
```

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-02/ex5.c
> +    return n * fatorial(n - 1);
```suggestion
        return n * fatorial(n - 1);
```

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-02/ex4.c
> +        if (x == y && y == z) printf("O tri�ngulo � equil�tero");
```suggestion
        if (x == y && y == z)
            printf("O triângulo é equilátero");
```

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-02/ex4.c
> +        else if (x != y && y != z && x != z) printf("O tri�ngulo � escaleno");
```suggestion
        else if (x != y && y != z && x != z)
            printf("O triângulo é escaleno");
```

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-02/ex4.c
> +        else printf("O tri�ngulo � is�sceles");
```suggestion
        else
            printf("O triângulo é isósceles");
```

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-02/ex6.c
> +    printf("%d elevado a %d: %d", a, b, exp(a, b));
```suggestion
    printf("%d elevado a %d: %d\n", a, b, exp(a, b));
```

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-02/ex7.c
> +int mult(int a, int b)
```suggestion
int multiplica(int a, int b)
```
```suggestion
int multiply(int a, int b)
```

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-02/ex7.c
> +int imprimir(int a)
as the 1 is not doing anything really, you can tell the C compiler that it returns nothing
```suggestion
void imprimir(int a)
```

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-02/ex7.c
> +    return 1;
and than, actually return nothing
```suggestion
```

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-03/ex1.c
> +    for(int i = 0; i < 20; i++) {
every part of this program could be a function, what do you think?

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-03/ex1.c
> +    printf("Media dos valores: %d", media);
```suggestion
    printf("Media dos valores: %d\n", media);
```

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-03/ex1.c
> +    int maior = 0;
if the user inputs a negative number this program returns the wrong value, try setting the starting value form `maior` to the lowest value an int variable can hold: [−32,767](https://en.wikipedia.org/wiki/C_data_types)
```suggestion
    int maior = -32767;
```

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-03/ex1.c
> +    printf("Maior valor encontrado: %d\n", maior);
also, if the user inputed only odd numbers this output would be wrong too, I'd put an if before giving this outputs like `if (input <= 0) { return 0; }`
```suggestion
    if (input <= 0) {
        return 0;
    }
    printf("Maior valor encontrado: %d\n", maior);
```

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-03/ex10.c
> +
```suggestion
```

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-03/ex10.c
> +
```suggestion
```

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-03/ex10.c
> +    int vetor[10], num, index_z = 9, index = 0;
nice solution, really simple and great! :tada:

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-03/ex11.c
> +            if(vetor[i] == vetor[j] && (i != j)) {
nice, but I would do the following:

```c
        int cont = 0;
        for(int j = 0; j < n; j++) {
            if(vetor[i] == vetor[j]) {
```

what do you think?

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-03/ex2.c
> +int bin_to_dec(int *vetor) {
well, the exercice description dictates this signature, tho. not that this is wrong :man_shrugging: 
```suggestion
int transforma_binario_decimal(int vetor[5]) {
```

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-03/ex2.c
> +    for(int i = 0; i < 5; i++) {
ok, nice, tho I'd prefer a downwards for loop, like this:

```c
    int base = 1, q = 0, result = 0;
    for(int index = 5; index >= 0; index--) {
```

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-03/ex2.c
> +        q = vetor[index] * base;
I'd advocate too, that you don't need this `q` variable

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-03/ex2.c
> +int main()
maybe it's better to rename this file to `ex2-e-3.c`?

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-03/ex5.c
> +        index++;
I don't think you are respecting the exercise here. It's stated there that you should change the value of the vector and then display the final array.

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-03/ex6.c
> +            return 1;
I think it would be nice if you return 0 here and 1 if the value wasn't found :smile:

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-03/ex7.c
> +        printf("Digite um numero para o vetor a: ");
```suggestion
        printf("criar vetor a[%d] = ", i);
```

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-03/ex7.c
> +        printf("Digite um numero para o vetor b: ");
```suggestion
        printf("criar vetor b[%d] = ", i);
```

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-03/ex9.c
> +    int menor_volta = 0;
```suggestion
```

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-03/ex9.c
> +            menor_volta = i + 1;
```suggestion
```

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-03/ex9.c
> +    for(int i = 0; i < n; i++) {
```suggestion
    for(int i = 1; i < n; i++) {
```
you already is processing the first item in the first line of this function

2019-08-31 16:10 UTC, vhoyer commented on aula-pratica-03/ex9.c
> +
```suggestion
```

2019-09-01 00:03 UTC, joaocruz19 commented on aula-pratica-02/_
> +
Hey, i just see your comments here. You're right, we really should do this in portuguese, it's not all students that understand english after all. And thanks for your suggestions at the exercises ;) .

2019-09-01 00:15 UTC, vhoyer commented on aula-pratica-02/ex2.c
> +            return 0;
eu acho que vc tbm tem que alterar esse 0 para um `false` e aquele 1 ali em baixo para `true`

2019-09-01 00:15 UTC, vhoyer commented on aula-pratica-02/ex2.c
> +        if(primo(i)){
aqui vc tbm que alterar para ter o mesmo nome da função que vc criou

2019-09-01 00:16 UTC, vhoyer commented on aula-pratica-02/ex3.c
> +int n_divisores(int n);
tem essa linha aqui ainda, que acho que agr ela ficou até errada kkk

2019-09-01 00:55 UTC, vhoyer commented on aula-pratica-02/ex2.c
> +#include<stdbool.h>
precisa do bool aí?

2019-09-01 01:19 UTC, joaocruz19 commented on aula-pratica-02/ex2.c
> +#include<stdbool.h>
Creio que sim, sem ele não tava querendo compilar, ai eu pesquisei e vi que precisava usar...

2019-09-01 12:23 UTC, vhoyer commented on aula-pratica-02/ex3.c
> +            cont++;
se não quiser esse pode dar resolve nesse comentário

2019-09-01 12:44 UTC, vhoyer commented on aula-pratica-02/ex8.c
> +    }
aqui o que vc pode fazer é trocar todo o corpo dessa função por isso:

```c
return a % 2 == 0;
```

2019-09-01 12:44 UTC, vhoyer commented on aula-pratica-03/ex1.c
> +    int maior = 0;
esse ⬆️ e [esse](https://github.com/alunos-fatec-sjc/linguagem-de-programacao/pull/1/files#r319727729) comentários são bugs na vdd, então seria especialmente interessante vc corrigir isso 😅

2019-09-01 12:44 UTC, vhoyer commented on aula-pratica-03/ex10.c
> +        }
sabe isso?
```c
        if(num == 0) {
            vetor[index_z--] = num;
        }
        else {
            vetor[index++] = num;
        }
```
então, não é necessáriamente pra vc fazer, é mais pra te mostrar, mas esse bagulho aí de cima, pode ser isso aqui em baixo:
```c
        vetor[num == 0 ? index_z-- : index++] = num;
```

2019-09-01 12:44 UTC, vhoyer commented on aula-pratica-03/ex6.c
> +            return 1;
bom, isso derrota o propósito 😂 , 
```suggestion
            return 0;
```

2019-09-04 11:47 UTC, vhoyer commented on aula-pratica-02/ex4.c
> +        printf("O triângulo é equilátero");
```suggestion
            printf("O triângulo é equilátero");
```

2019-09-04 11:47 UTC, vhoyer commented on aula-pratica-02/ex4.c
> +         printf("O triângulo é escaleno");
```suggestion
            printf("O triângulo é escaleno");
```

2019-09-04 11:47 UTC, vhoyer commented on aula-pratica-02/ex4.c
> +         printf("O triângulo é isósceles");
```suggestion
            printf("O triângulo é isósceles");
```

2019-09-04 11:51 UTC, vhoyer commented
Cara, ta faltando tirar aquela linha em branco no exercicio 10 da lista 3, e essas identacoes que eu comentei agr, depois disso pode mergear ;), vlw d+ pela contrib xD

2019-09-04 11:52 UTC, vhoyer submitted a review, later dismissed

2019-09-04 12:03 UTC, vhoyer commented on aula-pratica-03/ex2-e-3.c
> +    int base = 1, q = 0, result = 0;
```suggestion
    int base = 1, result = 0;
```

2019-09-04 16:46 UTC, vhoyer commented on aula-pratica-02/ex4.c
> +            return 1;
aí tu exagerou, aí tava certo kkk, o lance é sempre manter 4 espaços (ou um tab) de identação entre um novo bloco e o bloco atual

2019-09-04 16:46 UTC, vhoyer commented on aula-pratica-03/ex10.c
> -
eu não to falando pra vc colocar de volta, as ter espaços lógicos assim é bom, só não é legal ter os espaços a mais no final do arquivo

2019-09-04 16:49 UTC, vhoyer commented
acho que isso é meio sem ponto, eu até faria pra vc, mas não tenho acesso ao seu branch, e tbm não quero deixar entrar com ele com a identação errada, desculpa aí, é que to acostumado com esse negocio de deixar passar algo pra master, e isso começa a gerar maus exemplos, sabe? não da pra ter um mau exemplo no código por uma semana que esse mau exemplo vira 5 quando vc vai olhar (quando vc trabalha com muita gente)

2019-09-04 21:31 UTC, joaocruz19 commented
Respondendo ao seu último comentário...eu acho legal quando vc faz essas correções pq ajuda bastante a ter boas práticas (principalmente pelo fato de eu ser novo na área :sweat_smile: ) e ter noções de como o pessoal que já tem uma experiência costuma fazer os códigos. :wink:

2019-09-04 23:24 UTC, vhoyer approved these changes

2019-09-04 23:24 UTC, merged